### ISSUE TITLE
Machine name

### ISSUE THREAD

**Issue by saravandekerke** [holmrenser/IOGA#3]
Hoi Rens,

Klopt het dat je nog wel de machine name moet aangeven? Ik zet in ieder geval in de terminal steeds -m FCC. Dat leek te helpen.

Sara

**Comment by Lilian-ufsc** [comment]
Hi Rens,

I have a problem! I'm using IOGA.py, but I keep seeing this error: OSError: [Errno 2]. Would you please help me solve this problem?

[teste] Quality trimming with BBduk

Traceback (most recent call last):

File "./IOGA.py", line 408, in <module> main(args.reference,args.name,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)

File "./IOGA.py", line 352, in main

source,FP,RP,final_iteration = IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)

File "./IOGA.py", line 288, in IOGA_loop

forward,reverse = run_bbduk(name,forward,reverse,threads)

File "./IOGA.py", line 187, in run_bbduk subprocess.call(['bbduk.sh','ref='+adapterdir,'in='+forward,'in2='+reverse,'out='+FP,'out2='+RP,'threads='+threads,'k=25','ktrim=rl','qtrim=t','minlength=32','-Xmx10G'],stderr=fnull,stdout=fnull)

File "/usr/lib/python2.7/subprocess.py", line 522, in call

return Popen(*popenargs, **kwargs).wait()

File "/usr/lib/python2.7/subprocess.py", line 710, in __init__

errread, errwrite)

File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child

raise child_exception

OSError: [Errno 2] No such file or directory 

Best regards,

Lilian

**Comment by holmrenser** [comment]
@Lilian-ufsc I am opening a new issue for this. Let's continue there.

**Comment by Lilian-ufsc** [comment]
Ok! I will wait. Thank you so much.
