### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by wbyu** [holmrenser/IOGA#6]
Hi Renser,

When I was using this command "python IOGA.py -r ~/reference/reference.fasta -n name -1 file_1.fq -2 file_2.fq -i 300 -t 5 -m 0 -v" to run, an error was reported as below:

Traceback (most recent call last):
  File "/lustre/apps/bio-software/IOGA/IOGA.py", line 432, in <module>
    main(args.reference,args.name,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)
  File "/lustre/apps/bio-software/IOGA/IOGA.py", line 377, in main
    source,FP,RP,final_iteration = IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)
  File "/lustre/apps/bio-software/IOGA/IOGA.py", line 350, in IOGA_loop
    FP,RP = extract_reads(folder,prefix,rmdup_merged,forward,reverse)
  File "/lustre/apps/bio-software/IOGA/IOGA.py", line 179, in extract_reads
    for line in subprocess.check_output([config['samtools'],'view','-S',samfile],stderr=fnull).split('\n'):
  File "/lustre/apps/bio-software/Anaconda2/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/lustre/apps/bio-software/Anaconda2/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/lustre/apps/bio-software/Anaconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

Could you please tell me how to fix it? Thanks.

Best wishes,
Wen-Bin

**Comment by holmrenser** [comment]
Hi Wen-Bin,

It looks like the samtools that IOGA is running does not have the correct permissions, which results in the permission denied error. You can check what samtools is being used by IOGA by checking the config.json file in the folder where you installed IOGA.

Please let me know if you run into any additional problems.

**Comment by wbyu** [comment]
Hi Renser,

Thanks for your prompt reply. Yes, this problem is permissions of samtools. It has fixed out, so it is working well now. Thank you again.
 Best, 
Wen-Bin
